config/routes.rb
Rails.application.routes.draw do
 
 root 'static_pages#home'
 
 get 'about' => 'static_pages#about'
 
 get 'contact' => 'static_pages#contact'

 get 'representatives' => 'representatives#reps'
 
 resources :newsletter_subscriptions, only: [:create]
 









end

app/models/newsletter_subscription.rb
class NewsletterSubscription < ActiveRecord::Base
  # create unsubscribe_digest migration
  attr_accessor :unsubscribe_token
  after_create  :create_unsubscribe_digest
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }
                    
  def NewsletterSubscription.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def NewsletterSubscription.new_token
    SecureRandom.urlsafe_base64
  end
  
  def create_unsubscribe_digest
    self.unsubscribe_token = NewsletterSubscription.new_token
    update_attribute(:unsubscribe_digest, NewsletterSubscription.digest(unsubscribe_token))
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/newsletter_subscriptions_controller.rb
class NewsletterSubscriptionsController < ApplicationController
  
  def create
    @newsletter_subscription = NewsletterSubscription.new(newsletter_subscription_params
    )
    if @newsletter_subscription.save
      flash[:success] = "You're all signed up!"
      redirect_to root_url
      
    else
      render 'static_pages/home'
    end
    
  end
  
  private
    
    def newsletter_subscription_params
      params.require(:newsletter_subscription).permit(:email)
    end
end

app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController
	
	def reps
		@address = "#{params[:city]} #{params[:state]}" 		# Formats params information in a way that can be used by Sunlight Foundation API
		@reps = CLIENT.legislators_locate(@address).results		# Stores Sunlight API information in instance variable
		# @rep = CLIENT.legislators_lcate(params[:address], params[:state])
		
		# get latitude and longitude using google maps api and store in instance variables, see if you can get away with local variables
		gmaps_response = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{params[:state]}+#{params[:city]}&key=AIzaSyCJjdXuDzjx5tOcYNHKuNQLAfeIya566pA")
		@lat = "%.2f" % gmaps_response.parsed_response["results"][0]["geometry"]["location"]["lat"]
		@lng = "%.2f" % gmaps_response.parsed_response["results"][0]["geometry"]["location"]["lng"]

		# here you'll pass the latitude and longitude into the open states api
		@state_reps = (HTTParty.get("http://openstates.org/api/v1/legislators/geo/?lat=#{@lat}&long=#{@lng}&apikey=fc3288f6fc76432cab18b7a00cb4f3a9")).parsed_response
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @newsletter_subscription = NewsletterSubscription.new
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

def us_states
		[
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
	end
end

app/helpers/newsletter_subscriptions_helper.rb
module NewsletterSubscriptionsHelper
end

app/helpers/representatives_helper.rb
module RepresentativesHelper
	def city_state
		params[:city] + ", " + params[:state]
	end

	def full_title(rep)
		"#{rep.title}. #{rep.first_name} #{rep.last_name} (#{rep.party})"
	end

	def portrait(rep)
		"https://theunitedstates.io/images/congress/225x275/#{rep.bioguide_id}.jpg"
	end

	def rep_facebook(rep)
		if rep.facebook_id
			link_to("https://www.facebook.com/#{rep.facebook_id}", target: "_blank") do
				content_tag(:i, "", class: "fa fa-facebook-official fa-lg rep-facebook contact-link")
			end
		end
	end

	def rep_twitter(rep)
		if rep.twitter_id
			link_to("https://www.twitter.com/#{rep.twitter_id}", target: "_blank", class: "contact-link") do
				content_tag(:i, "", class: "fa fa-twitter fa-lg rep-twitter")
			end
		end
	end

	def rep_email(rep)
		if rep.oc_email
			mail_to("#{rep.oc_email}") do 
				content_tag(:i, "", class: "fa fa-envelope fa-lg contact-link")
			end
		end
	end

	def rep_phone(rep)
		if rep.phone
			link_to("tel:#{rep.phone}") do
				content_tag(:i, "", class: "fa fa-phone fa-lg contact-link")
			end
		end
	end

	def state_rep_phone(rep)
		link_to("tel:#{rep["offices"][0]["phone"]}") do
			content_tag(:i, "", class: "fa fa-phone fa-lg")
		end
	end

	def state_rep_full_title rep
		"#{rep["full_name"]} (#{rep["party"][0]})"
	end

	# create method for handling broken photo urls
	def state_rep_portrait state_rep
		state_rep_url = HTTParty.get(state_rep["photo_url"])
		if state_rep_url.code == 404
			image_tag("profile_placeholder.png", class: "img-roudned state-rep-portrait")
		else
			image_tag(state_rep["photo_url"], class: "img-rounded rep-portrait loaded")
		end
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
    <span class="navbar-brand"><%= link_to "VOICES", root_path, id: "logo" %> </span>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Will it work?", "#" %> </li>
        </ul>
      </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoicesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Google font -->
  <%= google_webfonts_init({
    google: ['Muli']
  })%>
</head>
<body> 
 <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %> 
      <%= yield %>
    </div>
    <%= debug(params) %>
</body>
</html>

app/views/representatives/reps.html.erb
<%# Location search form %>
   <div class="row text-center">
      <%= render 'shared/rep_search'%> 
  </div>

<div class="col-xs-12">
	</br>
	<%# @reps.inspect %>
	<%= @lat.inspect %>
	<%= @lng.inspect %>
	<% @state_reps.each do |state_rep| %>
		<%= state_rep.keys %></br></br>
	<% end %>

	</br>
</div>
<% if @reps.any? %>		<%# Check to see if any representatives were found %>
	<h1 class="text-center city-state" data-state="<%= params[:state]%>" data-city="<%= params[:city] %>"> <%= city_state %> Representatives </h1>
	<div class="row text-center congressional-reps">
		<% @reps.each do |rep| %>
			<div class="col-xs-6 col-lg-4 representatives">
				<%= image_tag(portrait(rep), class: "img-rounded rep-portrait") %>
				<div class="row">
					<h4 class="rep-title col-xs-offset-3 col-xs-6 col-lg-8 col-lg-offset-2"> <%= full_title(rep) %> </h4>
					
					<%# All representative contact links go here adjusts to whether or not rep has social links. Change icon colors %>
					<p class="rep-contact col-xs-12">
						<%= rep_twitter(rep) %>
						<%= rep_facebook(rep) %>
						<%= rep_email(rep) %>
						<%= rep_phone(rep) %>
					</p>
					<p class="col-xs-12">Term Ends: <%= rep.term_end.to_datetime.strftime('%B %e, %Y') %></p>
				</div>
			</div>
		<% end %>
	</div>

	<%# add classes to insert stage legislator information %>
	<div class="row text-center state-reps">
		<% @state_reps.each do |state_rep| %>
			<div class="col-xs-6 col-lg-4">
				<%# Add method that inputs default image for broken photo url %>
				<%= state_rep_portrait(state_rep) %>
				<h4 class="rep-title col-xs-offset-3 col-xs-6 col-lg-8 col-lg-offset-2"> <%= state_rep_full_title state_rep %> </h4>
				<p class="col-xs-12"><%= state_rep_phone(state_rep) %></p>
			</div>
		<% end %>
	</div>

<%# If no representatives are found, this message will be displayed %>
<% else %>
	<h1 class="text-center">Sorry, couldn't find representatives for <%= city_state %></h1>
<%end%>

app/views/shared/_error_messages.html.erb
<% if @newsletter_subscription.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@newsletter_subscription.errors.count, "error") %>.
    </div>
    <ul>
      <% @newsletter_subscription.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_rep_search.html.erb
<div class="col-xs-12 col-xs-offset-0 col-md-6 col-md-offset-3">
        <%= form_tag representatives_path, method: :get, class: "form-inline", role: "form" do %>
          <div>
            <%= text_field_tag :city, nil, class: 'form-control', placeholder: 'Enter Your City', required: true %>
            <%= select_tag :state, options_for_select(us_states), class: 'form-control' %>
            <%= submit_tag "Search", class: 'btn my-btn' %>
          </div>
        <% end %>
 </div>

app/views/static_pages/about.html.erb
<body>
  <div class="page-header">
    <h1>About Voices</h1>
  </div>  
    <ul class="about-list">
      <li>Voices is a tool to increase political participation</li>
      
    </ul>
</body>

app/views/static_pages/contact.html.erb
<body>
  
  <p> Contact chur bois </p>
  
</body>

app/views/static_pages/home.html.erb
    <div class="text-center jumbotron">
      <h1>All politics are local.</h1>
    </div>

    <div class="text-center row">
      
      <h2 class="col-xs-12">Search For Your Representatives</h2>
      
      <%# Location search form %>
      <%= render 'shared/rep_search'%>
    
    </div>

    <%# Newsletter sign up %>
    <div class=" text-center row signup-form home-row">
        <h2>Finna hear more?</h2>
        <div class="col-xs-12 col-xs-offset-0 col-md-6 col-md-offset-3">
          <%= form_for(@newsletter_subscription, url: newsletter_subscriptions_path, :html=> {:class => "form-inline"}) do |f| %>
            <%= render 'shared/error_messages' %>
            
            <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
            
            <%= f.submit "Sign up", class: 'btn my-btn' %>
          <% end %>
        </div>
    </div>
      
      <%# Download badge for the app store %>
      <div class="text-center row">
        <div class="app_badge">
          <%= link_to image_tag("app_store_badge.png", alt: "Download in the App Store", size:"250x100"), "itms://itunes.apple.com/us/app/apple-store/voices-for-iphone/id965692648?mt=8&uo=4" %>
        </div>
      </div>